"""Seed data for the style template catalogue (requirements v1.0, sections 4-7).

Each template is one composable dimension of a look: a hairstyle, a hair colour,
a makeup template, a beard style or a nail design. Complete looks are presets
that combine template IDs (section 16), they have no prompt of their own.

`description` is the short text shown in the app; `prompt` is the concrete
instruction the image model follows when no reference photo is used.

Seeds are inserted into the database on start-up when their ID is missing, so
admins can edit, archive or add templates without these values overwriting them.
Only add a reference image when the photo really shows that style.
"""
import re
from typing import Dict, List

ALL_SHAPES = ["oval", "round", "square", "heart", "diamond", "oblong"]
ALL_TEXTURES = ["straight", "wavy", "curly", "coily"]


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


def _shapes(text: str) -> List[str]:
    return list(ALL_SHAPES) if text == "all" else [s.strip() for s in text.split(",")]


def _hair(group, name, description, prompt, shapes, length, textures, finish, maintenance, occasions, features,
          image=None, featured=False):
    return {
        "id": f"hair_{group}_{_slug(name)}",
        "category": "Hairstyle",
        "group": group,
        "name": name,
        "description": description,
        "prompt": prompt,
        "face_shapes": _shapes(shapes),
        "lengths": length.split(","),
        "textures": ALL_TEXTURES if textures == "all" else textures.split(","),
        "finish": finish,
        "maintenance": maintenance,
        "occasions": occasions.split(","),
        "features": features.split(",") if features else [],
        "images": {"front": image} if image else {},
        "featured": featured,
    }


M = "men"
W = "women"

MEN_HAIR = [
    _hair(M, "Buzz Cut", "Very short, uniform cut",
          "an even buzz cut of about 6 mm all over with a clean, natural hairline",
          "oval,square,diamond", "very short", "all", "natural", "low", "everyday,professional", "", featured=True),
    _hair(M, "Crew Cut", "Short top with tapered sides",
          "a crew cut: 2-3 cm on top, slightly longer at the front, tapered short on the sides and back",
          "oval,square,heart", "short", "all", "natural", "low", "everyday,professional", "taper"),
    _hair(M, "French Crop", "Short top with forward fringe",
          "a French crop: short faded sides, 3-4 cm textured top pushed forward into a short straight fringe",
          "oval,round,square", "short", "straight,wavy", "textured", "low", "everyday,creative", "fringe,fade"),
    _hair(M, "Textured Crop", "Short, piecey texture on top",
          "a textured crop: mid fade on the sides, 4 cm choppy, piecey texture on top with a matte finish",
          "oval,round,square", "short", "straight,wavy,curly", "textured", "low", "everyday,creative", "fade,fringe",
          featured=True),
    _hair(M, "Caesar Cut", "Short cut with small forward fringe",
          "a Caesar cut: hair 2-3 cm all over combed forward into a short, straight horizontal fringe",
          "oval,square,oblong", "short", "straight,wavy", "natural", "low", "everyday,professional", "fringe"),
    _hair(M, "Ivy League", "Neat short cut with side-part length",
          "an Ivy League cut: short tapered sides, 4-5 cm on top at the front, neatly side-parted and swept",
          "oval,square,heart", "short", "straight,wavy", "structured", "medium", "professional,formal", "part,taper"),
    _hair(M, "Classic Taper", "Gradually shorter sides and back",
          "a classic taper: sides and back gradually shorter down to the neckline, 3-4 cm on top neatly combed",
          "oval,square,oblong", "short", "all", "natural", "low", "everyday,professional,formal", "taper",
          featured=True),
    _hair(M, "Low Taper Fade", "Subtle taper around sideburns and neckline",
          "a low taper fade only around the sideburns and neckline, the rest of the hair kept at its length on top",
          "oval,round,square,heart", "short,medium", "all", "natural", "medium", "everyday,professional", "fade,taper"),
    _hair(M, "Mid Fade", "Fade begins around middle of sides",
          "a mid fade starting halfway up the sides, blending into 4-5 cm on top",
          "oval,round,square", "short", "all", "textured", "medium", "everyday,creative", "fade"),
    _hair(M, "High Fade", "Fade begins higher on sides",
          "a high fade starting near the temples, with 3-5 cm of hair left on top",
          "oval,square,oblong", "short", "all", "structured", "medium", "everyday,creative", "fade"),
    _hair(M, "Skin Fade", "Very short sides fading to skin",
          "a skin fade: sides and back blended down to bare skin, 3-4 cm on top",
          "oval,square,diamond", "very short,short", "all", "structured", "high", "everyday,creative", "fade"),
    _hair(M, "Burst Fade", "Curved fade around the ear",
          "a burst fade curving in a semicircle around each ear, longer hair kept at the back and on top",
          "oval,square,round", "short,medium", "wavy,curly,coily", "textured", "high", "creative", "fade"),
    _hair(M, "Temple Fade", "Taper focused around temples",
          "a temple fade: a tight taper only at the temples with a crisp hairline, the rest of the cut unchanged",
          "oval,round,square", "short", "all", "structured", "medium", "everyday,creative", "fade,taper"),
    _hair(M, "Classic Side Part", "Defined part with controlled volume",
          "a classic side part: tapered sides, 5-6 cm on top combed to one side from a clean, defined part",
          "oval,square,oblong", "short,medium", "straight,wavy", "sleek", "medium", "professional,formal", "part",
          featured=True),
    _hair(M, "Comb Over", "Hair directed across from a part",
          "a comb over: short sides, longer top combed across from a low side part with a smooth finish",
          "oval,square,round", "short,medium", "straight,wavy", "sleek", "medium", "professional,formal", "part"),
    _hair(M, "Textured Quiff", "Front section lifted with texture",
          "a textured quiff: short sides, 6-8 cm on top with the front lifted up and back with loose, matte texture",
          "oval,round,square", "medium", "straight,wavy", "textured", "medium", "everyday,creative", ""),
    _hair(M, "Classic Quiff", "Structured front height",
          "a classic quiff: tapered sides, the front 7-9 cm brushed up and back into smooth, structured height",
          "oval,square,heart", "medium", "straight,wavy", "structured", "high", "formal,creative", ""),
    _hair(M, "Pompadour", "Hair swept upward and backward",
          "a pompadour: short sides, long top swept upward and backward into a high, glossy roll at the front",
          "oval,round,square", "medium", "straight,wavy", "structured", "high", "formal,creative", ""),
    _hair(M, "Slicked Back", "Hair directed backward",
          "slicked-back hair: 8-10 cm on top combed straight back with a smooth, light-shine finish, tidy sides",
          "oval,square,oblong", "medium", "straight,wavy", "sleek", "medium", "professional,formal", ""),
    _hair(M, "Curtains", "Center-parted medium hair",
          "curtains: medium-length hair parted in the centre, falling to either side of the forehead to the cheekbones",
          "oval,square,heart", "medium", "straight,wavy", "natural", "medium", "everyday,creative", "part,fringe"),
    _hair(M, "Medium Layered Cut", "Medium layers for movement",
          "a medium layered cut: hair to the ears and collar with soft layers for movement and a natural finish",
          "oval,oblong,square", "medium", "straight,wavy", "natural", "medium", "everyday", "layers"),
    _hair(M, "Wavy Fringe", "Forward fringe with natural wave",
          "a wavy fringe: tapered sides, longer wavy top pushed forward into a loose fringe",
          "oval,square,oblong", "short,medium", "wavy,curly", "natural", "low", "everyday,creative", "fringe"),
    _hair(M, "Natural Curls", "Curly hair shaped with natural volume",
          "natural curls: curly hair shaped evenly with defined curls and natural volume, tidy around the ears",
          "oval,square,heart", "short,medium", "curly,coily", "natural", "medium", "everyday", ""),
    _hair(M, "Curly Top Fade", "Curly volume on top, shorter sides",
          "a curly top fade: tight fade on the sides with 5-6 cm of defined curls on top",
          "oval,round,square", "short,medium", "curly,coily", "textured", "medium", "everyday,creative", "fade",
          featured=True),
    _hair(M, "Undercut", "Longer top contrasted with shorter sides",
          "an undercut: sides and back clipped short with no blending, 8-10 cm on top styled back",
          "oval,square,heart", "medium", "straight,wavy", "structured", "medium", "creative", "fade"),
    _hair(M, "Faux Hawk", "Hair styled upward along center",
          "a faux hawk: short sides, a strip of longer hair along the centre styled upward to a soft peak",
          "oval,round,square", "short,medium", "straight,wavy", "textured", "medium", "creative", ""),
    _hair(M, "Modern Mullet", "Shorter front/sides with longer back",
          "a modern mullet: short textured front and sides, longer hair at the back reaching the collar",
          "oval,square,diamond", "medium", "straight,wavy,curly", "textured", "medium", "creative", "layers"),
    _hair(M, "Man Bun", "Longer hair tied into a bun",
          "long hair gathered back and tied into a neat bun at the crown, sides smooth",
          "oval,square,oblong", "long", "all", "natural", "medium", "everyday,creative", "tied-back"),
    _hair(M, "Shoulder-Length Layers", "Longer layered hair",
          "shoulder-length layered hair with a natural texture, tucked behind the ears",
          "oval,square,oblong", "long", "straight,wavy,curly", "natural", "medium", "everyday,creative", "layers"),
]

WOMEN_HAIR = [
    _hair(W, "Pixie Cut", "Short, compact silhouette",
          "a pixie cut: short, close-cropped sides and back with slightly longer, soft layers on top",
          "oval,heart,square", "very short,short", "straight,wavy", "natural", "medium", "everyday,professional", ""),
    _hair(W, "Textured Pixie", "Short cut with texture and movement",
          "a textured pixie: short sides, choppy piecey layers on top with movement and a side-swept fringe",
          "oval,round,heart", "short", "straight,wavy", "textured", "medium", "everyday,creative", "layers,fringe"),
    _hair(W, "French Bob", "Short bob, often with fringe",
          "a French bob: a jaw-length bob with a soft, slightly tousled edge and a short eyebrow-length fringe",
          "oval,heart,oblong", "short", "straight,wavy", "natural", "medium", "everyday,creative", "fringe,loose"),
    _hair(W, "Classic Bob", "Structured bob around jaw or chin",
          "a sleek chin-length bob with blunt ends and a polished, smooth finish",
          "oval,heart,oblong", "short", "straight,wavy", "sleek", "medium", "everyday,professional",
          "sleek", image="sample_short_bob.jpg", featured=True),
    _hair(W, "Textured Bob", "Bob with movement and texture",
          "a textured bob: chin-length with point-cut ends, lived-in texture and movement",
          "oval,square,heart", "short", "straight,wavy", "textured", "low", "everyday", "loose"),
    _hair(W, "Wavy Bob", "Bob-length hair with soft waves",
          "a wavy bob: chin-to-jaw length with soft, loose waves and a side part",
          "oval,square,round", "short", "straight,wavy,curly", "natural", "medium", "everyday,occasion", "loose"),
    _hair(W, "Long Bob (Lob)", "Bob extending toward shoulders",
          "a long bob (lob): collarbone length with a straight, slightly angled outline",
          "oval,round,heart,square", "medium", "all", "natural", "low", "everyday,professional", "loose",
          featured=True),
    _hair(W, "Layered Lob", "Shoulder-length cut with layers",
          "a layered lob: shoulder length with soft internal layers for movement around the face",
          "oval,square,heart", "medium", "all", "natural", "low", "everyday,professional", "layers,loose"),
    _hair(W, "Shoulder-Length Layers", "Layers around shoulder length",
          "shoulder-length hair with long, blended layers and a soft, natural finish",
          "oval,round,square,heart", "medium", "all", "natural", "low", "everyday,professional", "layers,loose"),
    _hair(W, "Shag Cut", "Layered, textured cut",
          "a shag cut: shoulder length with choppy, feathered layers, volume at the crown and a wispy fringe",
          "oval,square,oblong", "medium", "wavy,curly", "textured", "medium", "everyday,creative", "layers,fringe"),
    _hair(W, "Wolf Cut", "Shag-inspired cut with pronounced layers",
          "a wolf cut: heavy, choppy layers around the crown and face, thinner lengths towards the shoulders",
          "oval,round,square,heart", "medium", "straight,wavy,curly", "textured", "medium", "creative",
          "layers,fringe"),
    _hair(W, "Butterfly Cut", "Long overall length with shorter face-framing layers",
          "a butterfly cut: long hair with short face-framing layers from the cheekbones and bouncy volume",
          "oval,round,square,heart", "medium,long", "straight,wavy", "natural", "medium",
          "everyday,professional,occasion", "layers,loose", featured=True),
    _hair(W, "Long Layers", "Long hair with graduated layers",
          "long hair below the shoulders with graduated layers for movement and a smooth finish",
          "oval,round,square,oblong", "long", "all", "natural", "low", "everyday,professional", "layers,loose"),
    _hair(W, "Face-Framing Layers", "Shorter layers around the face",
          "face-framing layers: shorter layers starting at the chin that frame the face, the rest at its length",
          "oval,square,heart,round", "medium,long", "all", "natural", "low", "everyday,professional",
          "layers,loose"),
    _hair(W, "V-Cut Layers", "Long hair with V-shaped back outline",
          "long layered hair cut to a V-shaped point at the back, with soft layers around the face",
          "oval,square,oblong", "long", "straight,wavy", "natural", "medium", "everyday,occasion", "layers,loose"),
    _hair(W, "U-Cut Layers", "Long hair with rounded U-shaped outline",
          "long layered hair cut to a rounded U-shaped outline at the back, smooth and full",
          "all", "long", "all", "natural", "low", "everyday,occasion", "layers,loose"),
    _hair(W, "Sleek Straight", "Smooth straight finish",
          "smooth, sleek straight hair with a glossy finish and a centre part, no frizz",
          "all", "medium,long", "all", "sleek", "high", "professional,formal,occasion", "sleek"),
    _hair(W, "Beach Waves", "Loose, relaxed waves",
          "loose, tousled, textured beach waves with a relaxed, undone finish",
          "oval,square,heart,round", "medium,long", "straight,wavy", "textured", "medium", "everyday,occasion",
          "loose", image="sample_beach_waves.jpg", featured=True),
    _hair(W, "Glamour Waves", "Glossy, voluminous S-shaped waves",
          "long, glossy, voluminous S-shaped waves with soft face-framing layers",
          "oval,square,heart,oblong", "long", "straight,wavy", "structured", "high", "occasion,formal", "loose",
          image="sample_glamour_waves.jpg", featured=True),
    _hair(W, "Soft Curls", "Soft defined curls",
          "soft, defined curls from mid-length to the ends with a smooth, bouncy finish",
          "oval,square,heart,round", "medium,long", "all", "natural", "medium", "everyday,occasion", "loose"),
    _hair(W, "Defined Curls", "More pronounced curl definition",
          "pronounced, defined curls all over with full volume and minimal frizz",
          "all", "medium,long", "curly,coily,wavy", "natural", "medium", "everyday,occasion", "loose"),
    _hair(W, "Curtain Bangs", "Center-parted fringe blending into layers",
          "soft curtain bangs parted in the centre, sweeping to frame the cheekbones and blending into layers",
          "oval,square,heart,oblong", "medium,long", "straight,wavy", "natural", "medium", "everyday", "fringe"),
    _hair(W, "Wispy Bangs", "Light, airy fringe",
          "a light, airy, see-through fringe falling to the eyebrows, the rest of the hair unchanged",
          "oval,square,heart", "medium,long", "straight,wavy", "natural", "medium", "everyday", "fringe"),
    _hair(W, "Blunt Bangs", "Straight, defined fringe",
          "a straight, blunt, eyebrow-length fringe with a clean edge",
          "oval,oblong", "medium,long", "straight", "sleek", "high", "everyday,creative", "fringe"),
    _hair(W, "Side-Swept Bangs", "Fringe directed diagonally",
          "a long fringe swept diagonally across the forehead to one side",
          "round,square,heart,oblong", "medium,long", "straight,wavy", "natural", "medium", "everyday,professional",
          "fringe"),
    _hair(W, "High Ponytail", "Hair gathered high at back",
          "hair gathered smoothly into a high ponytail at the crown",
          "oval,round,heart", "medium,long", "all", "sleek", "low", "everyday,occasion", "tied"),
    _hair(W, "Low Ponytail", "Hair gathered near nape",
          "hair gathered into a neat low ponytail at the nape with a smooth top",
          "all", "medium,long", "all", "sleek", "low", "everyday,professional", "tied"),
    _hair(W, "Messy Bun", "Casual gathered bun",
          "a casual, loose messy bun at the crown with a few soft face-framing strands",
          "all", "medium,long", "all", "textured", "low", "everyday", "updo,tied"),
    _hair(W, "Sleek Bun", "Smooth, polished bun",
          "a smooth, polished bun at the back of the head with no flyaways",
          "all", "medium,long", "all", "sleek", "medium", "professional,formal", "updo,sleek"),
    _hair(W, "French Braid", "Classic woven braid",
          "a classic French braid starting at the hairline and running down the back of the head",
          "all", "medium,long", "all", "structured", "medium", "everyday,occasion", "braided"),
    _hair(W, "Dutch Braid", "Raised braid structure",
          "a Dutch braid: an inside-out braid that sits raised along the back of the head",
          "all", "medium,long", "all", "structured", "medium", "everyday,occasion", "braided"),
    _hair(W, "Fishtail Braid", "Fine woven braid pattern",
          "a fishtail braid with a fine woven pattern, worn over one shoulder",
          "all", "long", "all", "structured", "medium", "occasion", "braided"),
    _hair(W, "Crown Braid", "Braid arranged around head",
          "a braid wrapped around the head like a crown, with soft loose strands",
          "all", "medium,long", "all", "structured", "high", "occasion,formal", "braided,updo"),
    _hair(W, "Braided Updo", "Braids gathered into an updo",
          "an elegant braided updo gathered at the back with soft loose tendrils",
          "all", "medium,long", "all", "structured", "high", "occasion,formal", "braided,updo",
          image="sample_braided_updo.jpg"),
    _hair(W, "Bridal Updo", "Formal gathered hairstyle",
          "a formal bridal updo: hair gathered into a smooth, sculpted low updo with soft face-framing tendrils",
          "all", "medium,long", "all", "structured", "high", "formal,occasion", "updo"),
    _hair(W, "Chignon", "Low structured bun",
          "a chignon: a low, structured bun at the nape with a smooth, polished top",
          "all", "medium,long", "all", "sleek", "medium", "professional,formal", "updo,sleek"),
]


def _colour(group, name, description, prompt, hex_value, undertones, technique, families, featured=False):
    return {
        "id": f"colour_{group}_{_slug(name)}",
        "category": "Hair colour",
        "group": group,
        "name": name,
        "description": description,
        "prompt": prompt,
        "hex": hex_value,
        "undertones": undertones.split(","),
        "technique": technique,  # all-over | highlights | balayage | tips | blend
        "families": families.split(","),
        "featured": featured,
    }


WOMEN_COLOURS = [
    _colour(W, "Natural Black", "Deep natural-looking black", "a deep, natural-looking black with a soft shine",
            "#1C1A19", "neutral,cool", "all-over", "black"),
    _colour(W, "Soft Black", "Softer black appearance", "a soft black with a hint of brown, less harsh than jet black",
            "#2B2522", "neutral,cool", "all-over", "black"),
    _colour(W, "Espresso Brown", "Very deep brown", "a very deep espresso brown", "#3B2A22", "olive,neutral",
            "all-over", "brown"),
    _colour(W, "Dark Chocolate", "Rich dark brown", "a rich dark chocolate brown with warm depth", "#4A3026",
            "warm,neutral", "all-over", "brown"),
    _colour(W, "Mocha Brown", "Balanced brown", "a balanced mid mocha brown", "#6B4E3D", "neutral,olive",
            "all-over", "brown"),
    _colour(W, "Chestnut Brown", "Warm brown", "a warm chestnut brown with reddish-gold reflections", "#7B4A2D",
            "warm,olive", "all-over", "brown", featured=True),
    _colour(W, "Caramel Balayage", "Blended caramel highlights",
            "a caramel balayage: hand-painted caramel lightening from mid-lengths to ends, blended into the base",
            "#A8743F", "warm,olive", "balayage", "brown,blonde", featured=True),
    _colour(W, "Honey Blonde", "Golden blonde", "a golden honey blonde", "#C99A55", "warm", "all-over", "blonde"),
    _colour(W, "Beige Blonde", "Beige-toned blonde", "a soft beige blonde with neutral tones", "#D2B48C",
            "cool,neutral", "all-over", "blonde"),
    _colour(W, "Ash Brown", "Cool-toned brown", "a cool, smoky ash brown with no warmth", "#6E6259", "cool",
            "all-over", "brown"),
    _colour(W, "Copper", "Orange-red tone", "a vivid copper with orange-red tones", "#B5562B", "warm", "all-over",
            "red"),
    _colour(W, "Auburn", "Red-brown tone", "a rich auburn red-brown", "#7E3A26", "warm", "all-over", "red"),
    _colour(W, "Burgundy", "Deep red-purple tone", "a deep burgundy red-purple", "#5E1F2D", "cool,olive",
            "all-over", "red"),
    _colour(W, "Rose Brown", "Brown with muted pink tones", "a brown with muted rose-pink tones", "#7A5550",
            "cool,neutral", "all-over", "brown"),
    _colour(W, "Platinum Blonde", "Very light blonde", "a very light, icy platinum blonde", "#E6E1D3", "cool",
            "all-over", "blonde"),
    _colour(W, "Balayage", "Gradual blended color placement",
            "a natural balayage: soft, gradual lighter pieces from mid-lengths to ends, a few shades lighter than the base",
            "#9C7350", "neutral,warm", "balayage", "brown,blonde"),
    _colour(W, "Face-Framing Highlights", "Lighter sections near the face",
            "face-framing highlights: two lighter sections at the front framing the face, the rest of the colour unchanged",
            "#B08A5E", "neutral,warm", "highlights", "blonde,brown"),
]

MEN_COLOURS = [
    _colour(M, "Natural Black", "Natural-looking black", "a natural-looking black with a matte finish", "#1C1A19",
            "neutral,cool", "all-over", "black"),
    _colour(M, "Soft Black", "Softer black finish", "a soft black with a hint of brown", "#2B2522", "neutral,cool",
            "all-over", "black"),
    _colour(M, "Dark Brown", "Deep brown", "a deep natural dark brown", "#3E2C23", "neutral,olive", "all-over",
            "brown", featured=True),
    _colour(M, "Chocolate Brown", "Rich brown", "a rich chocolate brown", "#4E3427", "warm,neutral", "all-over",
            "brown"),
    _colour(M, "Ash Brown", "Cool-toned brown", "a cool ash brown with no warmth", "#6E6259", "cool", "all-over",
            "brown"),
    _colour(M, "Chestnut Brown", "Warm brown", "a warm chestnut brown", "#7B4A2D", "warm,olive", "all-over",
            "brown"),
    _colour(M, "Caramel Highlights", "Subtle lighter sections",
            "subtle caramel highlights on the top section only, blended into the base colour", "#A8743F",
            "warm,olive", "highlights", "brown,blonde"),
    _colour(M, "Salt and Pepper", "Mixed dark and gray", "a salt-and-pepper mix of dark hair and grey strands",
            "#8A8682", "neutral,cool", "blend", "grey"),
    _colour(M, "Silver Gray", "Cool silver-gray", "a cool, even silver grey", "#B8B8B6", "cool", "all-over",
            "grey"),
    _colour(M, "Platinum Blonde", "Very light blonde", "a very light, icy platinum blonde", "#E6E1D3", "cool",
            "all-over", "blonde"),
    _colour(M, "Copper Brown", "Warm copper-brown", "a warm copper brown", "#8A4A2A", "warm", "all-over",
            "red,brown"),
    _colour(M, "Burgundy Tint", "Subtle red-purple tone", "a subtle burgundy red-purple tint over the natural base",
            "#4F2229", "cool,olive", "all-over", "red"),
    _colour(M, "Frosted Tips", "Lighter tips on selected sections", "frosted tips: only the tips of the top section lightened to pale blonde",
            "#D8C9A8", "neutral", "tips", "blonde"),
    _colour(M, "Gray Blending", "Blends visible gray with natural color",
            "grey blending: visible grey strands softened so they blend with the natural colour, still natural-looking",
            "#7D7671", "warm,cool,neutral,olive", "blend", "grey,brown"),
]


def _makeup(group_name, name, description, prompt, occasions, intensity, undertones="", attributes="",
            featured=False):
    return {
        "id": f"makeup_{_slug(name)}",
        "category": "Makeup",
        "group": "all",  # makeup is never restricted by inferred gender (requirements 7)
        "subcategory": group_name,
        "name": name,
        "description": description,
        "prompt": prompt,
        "occasions": occasions.split(","),
        "intensity": intensity,  # natural | medium | bold
        "undertones": undertones.split(",") if undertones else [],
        "attributes": attributes.split(",") if attributes else [],
        "featured": featured,
    }


MAKEUP = [
    _makeup("Natural", "No-Makeup Makeup", "Minimal, natural-looking enhancement",
            "minimal makeup that looks like none: evened-out skin with sheer coverage, groomed brows, clear mascara, tinted lip balm",
            "everyday,professional", "natural", "", "foundation,brows,lips"),
    _makeup("Natural", "Natural Glow", "Soft radiant finish",
            "fresh, dewy skin with light coverage, soft brows, rosy cheeks and a tinted lip",
            "everyday", "natural", "warm,neutral", "foundation,blush,highlight,lips", featured=True),
    _makeup("Natural", "Soft Nude", "Neutral understated palette",
            "neutral nude makeup: soft taupe eyeshadow, thin brown liner, light mascara and a nude lip",
            "everyday,professional", "natural", "neutral,olive", "eyeshadow,eyeliner,lips"),
    _makeup("Everyday", "Office Makeup", "Subtle professional styling",
            "polished office makeup: even satin skin, defined brows, matte neutral eyeshadow, mascara and a muted rose lip",
            "professional", "medium", "", "foundation,brows,eyeshadow,lips", featured=True),
    _makeup("Everyday", "Fresh Everyday", "Light, fresh appearance",
            "fresh everyday makeup: light skin tint, a touch of peach blush, mascara and a glossy lip",
            "everyday", "natural", "warm", "foundation,blush,lips"),
    _makeup("Everyday", "Minimal Makeup", "Reduced intensity",
            "minimal makeup: concealer only where needed, brushed-up brows and a sheer lip colour",
            "everyday", "natural", "", "brows,lips"),
    _makeup("Glam", "Soft Glam", "Blended tones and moderate definition",
            "soft glam: warm neutral blended eyeshadow, soft winged liner, defined lashes, sculpted cheeks and a nude-pink lip",
            "occasion,evening", "medium", "warm,neutral", "eyeshadow,eyeliner,blush,lips", featured=True),
    _makeup("Glam", "Full Glam", "More pronounced makeup",
            "full glam: full-coverage skin, contour and highlight, dramatic eyeshadow, lashes and a defined lip",
            "occasion,evening,party", "bold", "", "foundation,contour,eyeshadow,eyeliner,lips"),
    _makeup("Glam", "Smokey Eye", "Darker blended eye makeup",
            "a smokey eye: blended charcoal eyeshadow, smudged liner on the waterline, full lashes and a neutral lip",
            "evening,party", "bold", "cool,neutral", "eyeshadow,eyeliner"),
    _makeup("Glam", "Cut Crease", "Defined eyeshadow structure",
            "a cut crease: a sharply defined crease line with a light lid colour and winged liner",
            "party,evening", "bold", "", "eyeshadow,eyeliner"),
    _makeup("Occasion", "Bridal", "Occasion-specific makeup",
            "long-wear bridal makeup: soft-matte flawless skin, shimmer lids, lashes, soft blush and a rose lip",
            "occasion,formal", "medium", "", "foundation,eyeshadow,blush,lips", featured=True),
    _makeup("Occasion", "Party", "Event-oriented styling",
            "party makeup: shimmer eyeshadow, winged liner, glowing highlight and a bold glossy lip",
            "party", "bold", "", "eyeshadow,eyeliner,highlight,lips"),
    _makeup("Occasion", "Evening", "Defined evening look",
            "evening makeup: defined bronze eyes, sculpted cheeks and a deep berry lip",
            "evening", "bold", "cool,olive", "eyeshadow,contour,lips"),
    _makeup("Occasion", "Festive", "Color and finish configurable",
            "festive makeup: jewel-toned shimmer eyeshadow, gold inner-corner highlight, kohl liner and a rich red lip",
            "occasion,party", "bold", "warm,olive", "eyeshadow,eyeliner,lips"),
    _makeup("Eye", "Winged Liner", "Defined winged eyeliner",
            "a clean black winged eyeliner flick on the upper lid, the rest of the face unchanged",
            "everyday,evening", "medium", "", "eyeliner"),
    _makeup("Eye", "Soft Smokey Eye", "Blended smoky eye",
            "a soft brown smokey eye, lightly blended, with mascara",
            "everyday,evening", "medium", "warm,neutral", "eyeshadow"),
    _makeup("Eye", "Graphic Liner", "Expressive liner",
            "graphic eyeliner: a bold, sharp geometric liner shape on the upper lid",
            "party,creative", "bold", "", "eyeliner"),
    _makeup("Lip", "Nude Lip", "Neutral lip color", "a creamy nude lip colour close to the natural lip tone",
            "everyday,professional", "natural", "warm,neutral,olive", "lips"),
    _makeup("Lip", "Rose Lip", "Muted rosy tone", "a muted rose lip colour", "everyday,professional", "natural",
            "cool,neutral", "lips"),
    _makeup("Lip", "Classic Red Lip", "Red statement lip", "a classic, matte statement red lip",
            "evening,party,formal", "bold", "", "lips", featured=True),
    _makeup("Lip", "Glossy Lip", "Gloss finish", "a sheer, glossy lip finish over the natural lip colour",
            "everyday,party", "natural", "", "lips"),
    _makeup("Finish", "Dewy", "Radiant finish", "a dewy skin finish with natural radiance, no heavy coverage",
            "everyday", "natural", "", "foundation"),
    _makeup("Finish", "Matte", "Reduced-shine finish", "a soft-matte skin finish that reduces shine, skin texture kept",
            "professional,formal", "natural", "", "foundation"),
    _makeup("Finish", "Satin", "Balanced finish", "a satin skin finish between matte and dewy",
            "everyday,professional", "natural", "", "foundation"),
    _makeup("Finish", "Radiant", "Luminous finish",
            "a luminous, radiant skin finish with highlight on the cheekbones", "occasion,evening", "medium", "",
            "foundation,highlight"),
]


def _beard(name, description, prompt, shapes, maintenance, occasions, featured=False):
    return {
        "id": f"beard_{_slug(name)}",
        "category": "Beard & grooming",
        "group": "men",
        "name": name,
        "description": description,
        "prompt": prompt,
        "face_shapes": _shapes(shapes),
        "maintenance": maintenance,
        "occasions": occasions.split(","),
        "featured": featured,
    }


BEARDS = [
    _beard("Full Beard", "Full, well-groomed beard",
           "a full, well-groomed beard about 2-3 cm long with a sharp cheek line and neckline",
           "oval,round,oblong,diamond", "high", "everyday,formal", featured=True),
    _beard("Short Boxed Beard", "Short beard with crisp edges",
           "a short boxed beard about 1 cm long with crisp edges and a connected moustache",
           "oval,round,square,heart", "medium", "everyday,professional,formal", featured=True),
    _beard("Designer Stubble", "Even few-days stubble",
           "even designer stubble of a few days' growth with a tidy neckline", "all", "low",
           "everyday,professional"),
    _beard("Goatee", "Chin beard with moustache",
           "a neat goatee: hair on the chin connected to a trimmed moustache, cheeks clean-shaven",
           "round,square,oval", "medium", "everyday,creative"),
    _beard("Classic Moustache", "Trimmed moustache, clean chin",
           "a trimmed classic moustache along the top lip, the rest of the face clean-shaven",
           "oval,oblong,heart", "medium", "everyday,creative"),
    _beard("Clean Shave", "Smooth, no facial hair", "a smooth, clean-shaven face with no facial hair", "all", "high",
           "professional,formal"),
]


def _nails(name, description, prompt):
    return {
        "id": f"nails_{_slug(name)}",
        "category": "Nail art",
        "group": "all",
        "name": name,
        "description": description,
        "prompt": prompt,
        "occasions": ["everyday", "occasion"],
        "featured": False,
    }


NAILS = [
    _nails("French Ombre", "Pink-to-white ombre", "a soft pink-to-white French ombre manicure"),
    _nails("Rose Gold Chrome", "Mirror rose gold", "mirror-finish rose gold chrome nails"),
    _nails("Classic Nude", "Glossy nude almond", "glossy classic nude almond nails"),
    _nails("Marble", "White marble with gold veins", "white marble nail art with fine grey and gold veins"),
]


def _look(group, name, description, parts, occasions, featured=False):
    return {
        "id": f"look_{group}_{_slug(name)}",
        "category": "Overall beauty look",
        "group": group,
        "name": name,
        "description": description,
        "parts": parts,  # template IDs combined by this look
        "occasions": occasions.split(","),
        "featured": featured,
    }


LOOKS = [
    _look(W, "Red Carpet", "Glamour waves with a classic red lip",
          ["hair_women_glamour_waves", "makeup_classic_red_lip"], "evening,formal", featured=True),
    _look(W, "Evening Gala", "Braided updo with a smokey eye",
          ["hair_women_braided_updo", "makeup_smokey_eye"], "evening,formal"),
    _look(W, "Bridal Luxe", "Bridal updo with bridal makeup", ["hair_women_bridal_updo", "makeup_bridal"],
          "formal,occasion"),
    _look(W, "Sunny Weekend", "Beach waves, honey blonde and natural glow",
          ["hair_women_beach_waves", "colour_women_honey_blonde", "makeup_natural_glow"], "everyday"),
    _look(W, "Office Ready", "Long bob with office makeup", ["hair_women_long_bob_lob", "makeup_office_makeup"],
          "professional"),
    _look(M, "Groom Look", "Side part with a short boxed beard",
          ["hair_men_classic_side_part", "beard_short_boxed_beard"], "formal", featured=True),
    _look(M, "Smart Classic", "Classic taper and a clean shave", ["hair_men_classic_taper", "beard_clean_shave"],
          "professional,formal"),
    _look(M, "Weekend Texture", "Textured crop with designer stubble",
          ["hair_men_textured_crop", "beard_designer_stubble"], "everyday"),
]


def seed_templates() -> List[Dict]:
    """All seed templates in display order, with status and version defaults."""
    out = []
    for i, t in enumerate(MEN_HAIR + WOMEN_HAIR + WOMEN_COLOURS + MEN_COLOURS + MAKEUP + BEARDS + NAILS + LOOKS):
        out.append(dict({"status": "published", "version": 1, "sort_order": i, "tags": []}, **t))
    return out
